# frozen_string_literal: true

source 'https://rubygems.org'

gem 'colorize'
gem 'dotenv'
gem 'rack'
gem 'sinatra'

group :test do
  gem 'rspec'
  gem 'rspec-shell-expectations'
  gem 'rack-test'
  gem 'rubocop'
end
