# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.name = "chef-habitat-cnunez"
  end

  # provisions a dynamic private key for this VM
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path "cookbooks"
    chef.add_recipe "setup"
  end

  # machine-specifc
  config.vm.synced_folder ENV['HOME']+"/Downloads", "/dl"
  config.vm.synced_folder ENV['HOME']+"/src", "/src"
end
